server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          predicates:
            - Path=/api/v1.0/students/**

management:
  endpoints:
    web:
      exposure:
        include: '*'