scrape_configs:
  - job_name: 'ChurchRegistrationMetrics'
    metrics_path: '/church-registration/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          application: 'Church Registration'

  - job_name: 'ChurchBlogMetrics'
    metrics_path: '/church-blog/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8091' ]
        labels:
          application: 'Church Blog'